{
 "title": "Spark - Data On EKS",
 "description": "Monitors spark and EKS metrics using Prometheus in Kubernetes",
 "tags": [
  "kubernetes",
  "prometheus",
  "spark",
  "aws",
  "eks",
  "emr-containers"
 ],
 "time": { "from": "2023-02-17T08:00:00.000Z", "to": "2023-02-23T07:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "c_arn",
    "label": "Cluster ARN",
    "query": {
     "query": "label_values(kube_node_info{},cluster_arn)"
    }
   },
   {
    "name": "vc_id",
    "label": "Virtual Cluster ID",
    "query": {
     "query": "spark_info{cluster_arn=~\"$c_arn\"}"
    }
   },
   { "name": "job_id", "label": "Job ID", "query": { "query": "spark_info{}" } },
   {
    "name": "Pod",
    "label": "Driver ID",
    "query": {
     "query": "spark_info{emr_containers_amazonaws_com_job_id=\"$job_id\",emr_containers_amazonaws_com_virtual_cluster_id=\"$vc_id\"}"
    }
   },
   {
    "name": "executor",
    "label": "Executor ID",
    "query": {
     "query": "kube_pod_info{created_by_name=\"$Pod\"}"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "kube_pod_info{created_by_name=\"$Pod\"}"
    }
   },
   {
    "name": "Pod_ip",
    "query": {
     "query": "kube_pod_info{pod=\"$Pod\"}"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "kube_pod_status_phase{pod=~\"$Pod\",container!=\"\"}"
    }
   },
   {
    "name": "driver_node",
    "query": {
     "query": "kube_pod_info{pod=\"$Pod\"}"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "kube_namespace_labels" } },
   { "name": "spark_version", "query": { "query": "spark_info{}" } },
   { "name": "driver_ns", "query": { "query": "spark_info{}" } },
   {
    "name": "job_runner_pod",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind=\"Job\",created_by_name=\"$job_id\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod State Timelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Phase State Timeline",
   "type": "state-timeline",
   "description": "The phase state timeline of all job pods (driver, executor(s) and job-runner)\n\nIf this graph looks convoluted, try selecting  less executors as it can only show so many pods at a time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(\nscalar(kube_pod_status_phase{pod=\"$Pod\", container!=\"\", phase=\"Failed\"}*5) + \nscalar(kube_pod_status_phase{pod=\"$Pod\",container!=\"\", phase=\"Pending\"}*3) + \nscalar(kube_pod_status_phase{pod=\"$Pod\",container!=\"\", phase=\"Running\"}*2) + \nscalar(kube_pod_status_phase{pod=\"$Pod\",container!=\"\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{pod=\"$Pod\",container!=\"\", phase=\"Unknown\"}*1)\n)",
     "legendFormat": "Driver"
    },
    {
     "expr": "label_replace(\n(\n(\n(sum(kube_pod_status_phase{pod=~\"$executor\",container!=\"\",phase=\"Pending\"}*3)by(pod)) + (sum(kube_pod_status_phase{pod=~\"$executor\",container!=\"\",phase=\"Running\"}*2)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",container!=\"\",phase=\"Succeeded\"}*4)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",container!=\"\",phase=\"Unknown\"}*1)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",container!=\"\",phase=\"Failed\"}*5)by(pod))\n)\nand on (pod)\nkube_pod_info{created_by_name=\"$Pod\"}\n),\"executor_id\",\"$1\",\"pod\", \".*-exec-(.*)\"\n)\n>0\n",
     "legendFormat": "Executor: {{executor_id}}"
    },
    {
     "expr": "scalar(kube_pod_status_phase{pod=\"$job_runner_pod\", container!=\"\", phase=\"Failed\"}*5) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\",container!=\"\", phase=\"Pending\"}*3) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", container!=\"\", phase=\"Running\"}*2) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\",container!=\"\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{pod=\"$job_runner_pod\", container!=\"\", phase=\"Unknown\"}*1)",
     "legendFormat": "JobRunner"
    }
   ]
  },
  { "title": "Metric Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Jobs in K8s Cluster",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(count(spark_info{emr_containers_amazonaws_com_virtual_cluster_id=\"$vc_id\"}>0)by(emr_containers_amazonaws_com_job_id))>0",
     "legendFormat": "Job: {{emr_containers_amazonaws_com_job_id}}"
    }
   ]
  },
  {
   "title": "Metric Ingestion",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{created_by_name=\"$Pod\",container!=\"\"}) by (created_by_name)",
     "legendFormat": "Executor Progress"
    },
    {
     "expr": "spark_info{emr_containers_amazonaws_com_job_id=\"$job_id\"}",
     "legendFormat": "Driver Progress"
    }
   ]
  },
  { "title": "Driver Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Driver IP Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "repeat": "Pod",
   "options": { "content": "# $Pod_ip" }
  },
  {
   "title": "Requested Driver Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{container=\"spark-kubernetes-driver\",pod=\"$Pod\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Requested Driver Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{container=\"spark-kubernetes-driver\",pod=\"$Pod\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Driver Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=\"$Pod\",container!=\"\"}>0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Driver CPU / Memory  usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Driver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "repeat": "Pod",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\navg(container_memory_working_set_bytes{pod=\"$Pod\",container!=\"\",container!=\"POD\"}) /\navg(kube_pod_container_resource_limits{pod=\"$Pod\",container!=\"\",container!=\"POD\",resource=\"memory\"})\n)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Driver CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$Pod\",container!=\"\"} [5m])) by (pod) / 1000 * 100",
     "legendFormat": "Used CPU"
    },
    {}
   ]
  },
  { "title": "Executor CPU /Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Executor :  Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(\n(avg(container_memory_working_set_bytes{pod!=\"\",pod=~\"$executor\",container!=\"POD\",container!=\"\"})by (pod)) / (avg(kube_pod_container_resource_limits{pod!=\"\",pod=~\"$executor\",container!=\"POD\",container!=\"\",resource=\"memory\"})by (pod))\nand on (pod) kube_pod_info{created_by_name=\"$Pod\"}\n) by (pod)"
    }
   ]
  },
  {
   "title": "Executor  :  CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$executor\",pod!=\"\"} [4m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod) / 1000 * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Network IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Driver Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$Pod\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$Pod\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$executor',node=~\"$Node\"}[2m]) and on (pod,node) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,node)",
     "legendFormat": "{{ pod }} {{node}} Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$executor',pod!=\"POD\",node=~\"$Node\"}[2m]) and on (pod,node) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,node)",
     "legendFormat": "{{ pod }} {{node}}  Received"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$Pod\"}[2m])) by (pod,device)",
     "legendFormat": "{{pod }} - {{device}} Read"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$executor\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,device)",
     "legendFormat": "{{pod }} - {{device}} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$executor\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,device)",
     "legendFormat": "{{pod }} - {{device}} Write"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$Pod\"}[2m])) by (pod,device)"
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 - label_replace(((avg_over_time(node_memory_MemFree_bytes{container!=\"\"}[5m]) + avg_over_time(node_memory_Cached_bytes{container!=\"\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{container!=\"\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{container!=\"\"}[5m])),\"host_ip\", \"$1\", \"instance\", \"(.*):.*\") and on (host_ip) kube_pod_info{created_by_name=\"$Pod\",container!=\"\"})",
       "legendFormat": "Node: {{host_ip}} - Executor"
      },
      {
       "expr": "(1 - label_replace(((avg_over_time(node_memory_MemFree_bytes{container!=\"\"}[5m]) + avg_over_time(node_memory_Cached_bytes{container!=\"\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{container!=\"\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{container!=\"\"}[5m])),\"host_ip\", \"$1\",\"instance\", \"(.*):.*\") and on (host_ip) kube_pod_info{pod=\"$Pod\",container!=\"\"})",
       "legendFormat": "Node: {{host_ip}} - Driver"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(1 - label_replace(sum(rate(node_cpu_seconds_total{mode=\"idle\",container!=\"\"}[5m]) ) by (cpu, instance), \"host_ip\", \"$1\",\"instance\", \"(.*):.*\")) by (host_ip) and on (host_ip) kube_pod_info{created_by_name=\"$Pod\"}",
       "legendFormat": "Node: {{host_ip}} - Executor"
      },
      {
       "expr": "avg(1 - label_replace(sum(rate(node_cpu_seconds_total{mode=\"idle\",container!=\"\"}[5m]) ) by (cpu, instance), \"host_ip\", \"$1\",\"instance\", \"(.*):.*\")) by (host_ip) and on (host_ip) kube_pod_info{pod=\"$Pod\"}",
       "legendFormat": "Node: {{host_ip}} - Driver"
      }
     ]
    },
    {
     "title": "Node Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sort_desc(label_replace(sum(rate(node_network_transmit_bytes_total{container!=\"\"}[5m])) by (instance),\"host_ip\", \"$1\",\"instance\", \"(.*):.*\") and on (host_ip) kube_pod_info{created_by_name=\"$Pod\"})",
       "legendFormat": "Node: {{host_ip}} - Executor"
      },
      {
       "expr": "sort_desc(label_replace(sum(rate(node_network_transmit_bytes_total{container!=\"\"}[5m])) by (instance),\"host_ip\", \"$1\",\"instance\", \"(.*):.*\") and on (host_ip) kube_pod_info{pod=\"$Pod\"})",
       "legendFormat": "Node: {{host_ip}} - Driver"
      }
     ]
    },
    {
     "title": "Node Network Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sort_desc(label_replace(sum(rate(node_network_receive_bytes_total{container!=\"\"}[5m])) by (instance),\"host_ip\", \"$1\",\"instance\", \"(.*):.*\") and on (host_ip) kube_pod_info{created_by_name=\"$Pod\"})",
       "legendFormat": "Node: {{host_ip}} - Executor"
      },
      {
       "expr": "sort_desc(label_replace(sum(rate(node_network_receive_bytes_total{container!=\"\"}[5m])) by (instance),\"host_ip\", \"$1\",\"instance\", \"(.*):.*\") and on (host_ip) kube_pod_info{pod=\"$Pod\"})",
       "legendFormat": "Node: {{host_ip}} - Driver"
      }
     ]
    },
    {
     "title": "Executor Spin Up by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(count(kube_pod_info{created_by_name=\"$Pod\",node!=\"\",container!=\"\"})by(node))",
       "legendFormat": "Node: {{node}} - Executor"
      },
      {
       "expr": "(count(kube_pod_info{pod=\"$Pod\",node!=\"\",container!=\"\"})by(node))",
       "legendFormat": "Node: {{node}} - Driver"
      }
     ]
    },
    {
     "title": "Node Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace((1-avg(node_filesystem_free_bytes{container!=\"\"}/node_filesystem_size_bytes{container!=\"\"})by(instance)),\"host_ip\", \"$1\", \"instance\", \"(.*):.*\") and on (host_ip) kube_pod_info{created_by_name=\"$Pod\",container!=\"\"}",
       "legendFormat": "Node: {{host_ip}} - Executor"
      }
     ]
    },
    {
     "title": "Node Disk Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "label_replace(sum(rate(node_disk_read_bytes_total{container!=\"\"}[5m]))by(instance),\"host_ip\",\"$1\",\"instance\", \"(.+):.*\") and on (host_ip) \nkube_pod_info{created_by_name=\"$Pod\",container!=\"\"}",
       "legendFormat": "Node: {{host_ip}} - Executor"
      },
      {
       "expr": "label_replace(sum(rate(node_disk_read_bytes_total{container!=\"\"}[5m]))by(instance),\"host_ip\",\"$1\",\"instance\", \"(.+):.*\") and on (host_ip) \nkube_pod_info{pod=\"$Pod\",container!=\"\"}",
       "legendFormat": "Node: {{host_ip}} - Driver"
      }
     ]
    },
    {
     "title": "Node Disk Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "label_replace(sum(rate(node_disk_written_bytes_total{container!=\"\"}[5m]))by(instance),\"host_ip\",\"$1\",\"instance\", \"(.+):.*\") and on (host_ip) \nkube_pod_info{created_by_name=\"$Pod\",container!=\"\"}",
       "legendFormat": "Node: {{host_ip}} - Executor"
      },
      {
       "expr": "label_replace(sum(rate(node_disk_written_bytes_total{container!=\"\"}[5m]))by(instance),\"host_ip\",\"$1\",\"instance\", \"(.+):.*\") and on (host_ip) \nkube_pod_info{pod=\"$Pod\",container!=\"\"}",
       "legendFormat": "Node: {{host_ip}} - Driver"
      }
     ]
    }
   ]
  },
  {
   "title": "Stages & Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{__name__=~\"metrics_.*_DAGScheduler_stage_runningStages_Value\",__name__=~\".*$job_id.*\"}",
       "legendFormat": "Running Stages"
      },
      {
       "expr": "{__name__=~\"metrics_.*_appStatus_stages_completedStages_Count\",__name__=~\".*$job_id.*\"}",
       "legendFormat": "Completed Stages"
      },
      {
       "expr": "{__name__=~\"metrics_.*_appStatus_stages_failedStages_Count\",__name__=~\".*$job_id.*\"}",
       "legendFormat": "Failed Stages"
      }
     ]
    },
    {
     "title": "Completed Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "metrics_executor_completedTasks_total{pod=\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor ID: {{executor_id}}"
      }
     ]
    },
    {
     "title": "Failed Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "metrics_executor_failedTasks_total{pod=\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor ID: {{executor_id}}"
      }
     ]
    },
    {
     "title": "Current Active Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "metrics_executor_activeTasks{pod=\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor: {{executor_id}}"
      }
     ]
    },
    {
     "title": "Skipped Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "{__name__=~\"metrics_.*_appStatus_tasks_skippedTasks_Count\",__name__=~\".*$job_id.*\"}",
       "legendFormat": "Tasks"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark External Shuffle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spark Shuffle Data Written",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_executor_totalShuffleWrite_bytes_total{pod=~\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor: {{executor_id}}"
      }
     ]
    },
    {
     "title": "Spark Shuffle Data Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_executor_totalShuffleRead_bytes_total{pod=~\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor: {{executor_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap / Non - Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(metrics_executor_JVMHeapMemory_bytes{pod=\"$Pod\"})by(executor_id)",
       "legendFormat": "Executor: {{executor_id}}"
      },
      {
       "expr": "jvm_memory_bytes_used{pod=~\"^$executor$\",area=\"heap\"}",
       "legendFormat": " {{ pod }} "
      }
     ]
    },
    {
     "title": "JVM Off Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_executor_JVMOffHeapMemory_bytes{pod=\"$Pod\"}",
       "legendFormat": "Executor: {{executor_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Miscellaneous Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors Spawned",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_info{created_by_name=~\"$Pod\",container!=\"\"})",
       "legendFormat": "Executor Counts "
      }
     ]
    },
    {
     "title": "Packets Dropped : Network",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_network_receive_packets_dropped_total{pod=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod}} - Receive"
      },
      {
       "expr": "container_network_transmit_packets_dropped_total{pod=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod}} - Transmit"
      }
     ]
    }
   ]
  }
 ]
}