# Pre-requisite before running this job
# 1/ Open taxi-trip-execute.sh and update us-west-2-193481311148-spark-team-a and <REGION>
# 2/ Replace us-west-2-193481311148-spark-team-a with your S3 bucket created by this blueprint(Check Terraform outputs)
# 3/ execute taxi-trip-execute.sh

---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: taxi-trip-nvme-{{ds}}-{{task_instance.job_id}}
  namespace: spark-team-a
  labels:
    app: "taxi-trip-nvme"
    applicationId: "taxi-trip-nvme"
    queue: root.test
spec:
#  To create Ingress object for Spark driver.
#  Ensure Spark Operator Helm Chart deployed with Ingress enabled to use this feature
#  sparkUIOptions:
#    servicePort: 4040
#    servicePortName: taxi-trip-ui-svc
#    serviceType: ClusterIP
#    ingressAnnotations:
#      kubernetes.io/ingress.class: nginx
#      nginx.ingress.kubernetes.io/use-regex: "true"
  type: Python
  sparkVersion: "3.2.1"
  mode: cluster
  image: "public.ecr.aws/r1l5w1y9/spark-operator:3.2.1-hadoop-3.3.1-java-11-scala-2.12-python-3.8-latest"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "s3a://us-west-2-193481311148-spark-team-a/taxi-trip/scripts/pyspark-taxi-trip.py"  # MainFile is the path to a bundled JAR, Python, or R file of the application
  arguments:
    - "s3a://us-west-2-193481311148-spark-team-a/taxi-trip/input/"
    - "s3a://us-west-2-193481311148-spark-team-a/taxi-trip/output/"
  hadoopConf:
    "fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
    "fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "mapreduce.fileoutputcommitter.algorithm.version": "2"
  sparkConf:
    "spark.app.name": "taxi-trip-nvme"
    "spark.kubernetes.driver.pod.name": "taxi-trip-nvme-driver"
    "spark.kubernetes.executor.podNamePrefix": "taxi-trip-nvme"
    "spark.local.dir": "/data1"
    "spark.speculation": "false"
    "spark.network.timeout": "2400"
    "spark.hadoop.fs.s3a.connection.timeout": "1200000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.maximum": "200"
    "spark.hadoop.fs.s3a.fast.upload": "true"
    "spark.hadoop.fs.s3a.readahead.range": "256K"
    "spark.hadoop.fs.s3a.input.fadvise": "random"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"

    # Spark Event logs
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://us-west-2-193481311148-spark-team-a/spark-event-logs"
    "spark.eventLog.rolling.enabled": "true"
    "spark.eventLog.rolling.maxFileSize": "64m"
#    "spark.history.fs.eventLog.rolling.maxFilesToRetain": 100

    # Expose Spark metrics for Prometheus
    "spark.ui.prometheus.enabled": "true"
    "spark.executor.processTreeMetrics.enabled": "true"
    "spark.kubernetes.driver.annotation.prometheus.io/scrape": "true"
    "spark.kubernetes.driver.annotation.prometheus.io/path": "/metrics/executors/prometheus/"
    "spark.kubernetes.driver.annotation.prometheus.io/port": "4040"
    "spark.kubernetes.driver.service.annotation.prometheus.io/scrape": "true"
    "spark.kubernetes.driver.service.annotation.prometheus.io/path": "/metrics/driver/prometheus/"
    "spark.kubernetes.driver.service.annotation.prometheus.io/port": "4040"
    "spark.metrics.conf.*.sink.prometheusServlet.class": "org.apache.spark.metrics.sink.PrometheusServlet"
    "spark.metrics.conf.*.sink.prometheusServlet.path": "/metrics/driver/prometheus/"
    "spark.metrics.conf.master.sink.prometheusServlet.path": "/metrics/master/prometheus/"
    "spark.metrics.conf.applications.sink.prometheusServlet.path": "/metrics/applications/prometheus/"
    "spark.decommission.enabled": "true"
    "spark.storage.decommission.rddBlocks.enabled": "true"
    "spark.storage.decommission.shuffleBlocks.enabled" : "true"
    "spark.storage.decommission.enabled": "true"
    "spark.storage.decommission.fallbackStorage.path": "s3a://us-west-2-193481311148-spark-team-a/taxi-trip/fallbackStorage/"

  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 1
    onSubmissionFailureRetryInterval: 10

  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local1

  driver:
    podSecurityContext:
      fsGroup: 185
    volumeMounts: # Points to InstanceStore 150GB NVMe SSD for shuffle spill over from memory
      - name: spark-local-dir-1
        mountPath: /data1
        readOnly: false
    initContainers:
      - name: volume-permissions
        image: public.ecr.aws/docker/library/busybox
        command: [ 'sh', '-c', 'chown -R 185 /data1' ]
        volumeMounts:
          - mountPath: "/data1"
            name: "spark-local-dir-1"
    cores: 1
    coreLimit: "1200m"
    memory: "2g"
    serviceAccount: spark-team-a
    labels:
      version: 3.2.1
    nodeSelector:
      NodeGroupType: "spark-team-a-nvme"
      karpenter.sh/capacity-type: "on-demand"
    tolerations:
      - key: "spark-team-a-nvme"
        operator: "Exists"
        effect: "NoSchedule"
  executor:
    podSecurityContext:
      fsGroup: 185
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /data1
        readOnly: false
    initContainers:
      - name: volume-permissions
        image: public.ecr.aws/docker/library/busybox
        command: [ 'sh', '-c', 'chown -R 185 /data1' ]
        volumeMounts:
          - mountPath: "/data1"
            name: "spark-local-dir-1"
    cores: 1
    coreLimit: "1200m"
    instances: 4
    memory: "4g"
    serviceAccount: spark-team-a
    labels:
      version: 3.2.1
    nodeSelector:
      NodeGroupType: "spark-team-a-nvme"
      karpenter.sh/capacity-type: "spot"
    tolerations:
      - key: "spark-team-a-nvme"
        operator: "Exists"
        effect: "NoSchedule"
#    affinity: #uncomment to spread one pod per node to see improvements in Shuffle Read. 
#      podAntiAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#        - labelSelector:
#            matchExpressions:
#            - key: app
#              operator: In
#              values:
#              - taxi-trip-nvme
#          topologyKey: "kubernetes.io/hostname"
